name: ummobile_sdk
description: The SDK package used in the UMMobile App to connect with the server.
version: 0.0.1-beta1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ummobile_custom_http: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dotenv: ^3.0.0
  
flutter:
