name: ummobile_sdk
description: The SDK package used in the UMMobile App to connect with the server.
version: 0.0.3
homepage: https://github.com/UMMobile/ummobile_sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ummobile_custom_http: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  dotenv: ^3.0.0
  
flutter:
