name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    environment: Testing
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        
      - name: Test package
        run: flutter test
        env:
          PASSWORD_STUDENT: ${{ secrets.PASSWORD_STUDENT }}
          PASSWORD_EMPLOYEE: ${{ secrets.PASSWORD_EMPLOYEE }}
          EXEC_ENV: 'github_actions'