name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    environment: Testing
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneMacos: "America/Monterrey"

      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        
      - name: Test package
        run: flutter test --coverage
        env:
          PASSWORD_STUDENT: ${{ secrets.PASSWORD_STUDENT }}
          PASSWORD_EMPLOYEE: ${{ secrets.PASSWORD_EMPLOYEE }}
          EXEC_ENV: 'github_actions'

      - name: Upload coverage to Codecov 
        uses: codecov/codecov-action@v1 
        with: 
          token: ${{ secrets.CODECOV_TOKEN }} 
          file: coverage/lcov.info