name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get
        
      - name: Test package
        run: flutter test
        env:
          PASSWORD_STUDENT: ${{ secrets.PASSWORD_STUDENT }}
          PASSWORD_EMPLOYEE: ${{ secrets.PASSWORD_EMPLOYEE }}
          EXEC_ENV: 'github_actions'